version: "3"

services:
  php:
    build:
      dockerfile: "server/Dockerfile-PHP"
    image: web-tech-php
    volumes:
      - ./pages:/var/www/html
      - ./components:/var/www/components
    ports:
      - "80:80"
    links:
      - sql

  sql:
    build:
      dockerfile: "server/Dockerfile-SQL"
    image: web-tech-sql
    ports:
      - "3306:3306"
