FROM mysql

ENV MYSQL_ROOT_PASSWORD=4S&qx6tbCH&HS5RT
RUN mkdir -p /var/www/server
COPY server/mysql.docker /root/.my.cnf

COPY server/schema.sql /var/www/server/schema.sql
COPY tokens /var/www/tokens
COPY server/users.sh /var/www/server/users.sh
COPY server/triggers.sql /var/www/server/triggers.sql
COPY server/initial_data.sql /var/www/server/initial_data.sql
COPY server/scraped.sql /var/www/server/scraped.sql

RUN cd /var/www/server/ \
    && { \
         cat schema.sql; \
         bash users.sh; \
         cat triggers.sql; \
         cat initial_data.sql; \
         cat scraped.sql; \
       } > db.init \
    && rm *.sql users.sh

CMD ["mysqld", "--init-file=/var/www/server/db.init"]
